% A generic test bench script without any object under test.
% Generated by Audio Test Bench on 21-Mar-2023 20:28:53 UTC+01:00.

% Create test bench input and output
osc = audioOscillator('Frequency',300, ...
    'SamplesPerFrame',1024);
fileWriter = dsp.AudioFileWriter;

% Stream processing loop
maxIterations = 1000;
for iter = 1:maxIterations
    % Read from input, process, and write to output
    in = osc();
    out = in;
    fileWriter(out);
    
    % Uncomment to process callbacks if you are using parameterTuner:
    % drawnow limitrate
end

% Clean up
release(osc)
release(fileWriter)
